// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea.Data;

#nullable disable

namespace Tarea.Migrations.DepartamentoDb
{
    [DbContext(typeof(DepartamentoDbContext))]
    [Migration("20240217015319_Primer")]
    partial class Primer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tarea.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePersonal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Integrantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreDepartamento = "Ventas",
                            NombrePersonal = "Daniel, David, Exaul"
                        },
                        new
                        {
                            Id = 2,
                            NombreDepartamento = "Logistica",
                            NombrePersonal = "Carlos, Samuel, Ana"
                        },
                        new
                        {
                            Id = 3,
                            NombreDepartamento = "Seguridad",
                            NombrePersonal = "Pepe, Juan , Alex"
                        },
                        new
                        {
                            Id = 4,
                            NombreDepartamento = "Software",
                            NombrePersonal = "Betsabet, Luis, Lupe"
                        },
                        new
                        {
                            Id = 5,
                            NombreDepartamento = "Limpieza",
                            NombrePersonal = "Pedro, Lucas, Angel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
