// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea.Data;

#nullable disable

namespace Tarea.Migrations.CedulaDb
{
    [DbContext(typeof(CedulaDbContext))]
    [Migration("20240217015305_Primer")]
    partial class Primer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tarea.Models.Cedula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaPersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CedulaPersona = "8424668873",
                            Nombre = "Carlos"
                        },
                        new
                        {
                            Id = 2,
                            CedulaPersona = "7014641144",
                            Nombre = "Daniel"
                        },
                        new
                        {
                            Id = 3,
                            CedulaPersona = "5517840648",
                            Nombre = "David"
                        },
                        new
                        {
                            Id = 4,
                            CedulaPersona = "3694639581",
                            Nombre = "Exaul"
                        },
                        new
                        {
                            Id = 5,
                            CedulaPersona = "9998908281",
                            Nombre = "David"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
